### ISSUE TITLE
newest version but still "no BlasR out put"

### ISSUE THREAD

**Issue by sanvva** [aubombarely/Organelle_PBA#13]
===========================================================
 0) Checking arguments (Fri Aug 31 09:23:47 CST 2018)
============================================================

	Input PacBio reads file: R5.fq
	Input type: fastq
	Output directory: R5_organelle_PBA
	Organelle reference fasta file: NC_019616.fasta
		Organelle reference size: 176045 bp
		Repeat block size coverage detection: 1000
		Coverage ratio to define repeatitive region: 1.6
	Completeness fraction: 1.0
	Breaks overlap: 0
	Highest position to set up origin: 1
	Starting-End margin to check circularity: 10
	Overlap length to check circularity: 100
	Minimum BlasR alignment percentage: 5

============================================================
 1) Running BlasR (Fri Aug 31 09:23:48 CST 2018)
============================================================

	1.1- Converting Fastq to Fasta.
	      Using Seqtk to convert Fastq to Fasta.
	     Input PacBio read file contains 1423986 reads

	1.2- Running BlasR mapping.

No BlasR output was created.Please check the input and the running parameters.
[asa@node01 duj]$ ls R5_organelle_PBA/
01_1_BlasR_in.fasta

I've seen the same issue 1 year ago:
https://github.com/aubombarely/Organelle_PBA/issues/1
I've modified the two lines but still got the same error message.

HELP!

**Comment by aubombarely** [comment]
I have corrected the code in order of being able to use the last version of BlasR. The old versions of BlasR with which this program was designed used the arguments as -arg. New versions of Blasr use arguments as --arg, so it was the reason why it did not work (it was using -out instead --out). Please download the last version and try again. Let me know if does not work.

**Comment by sanvva** [comment]
@aubombarely I've updated your codes. It works!

**Comment by sanvva** [comment]
Oh no... ...
BlasR works but much slower than old codes.
**Still failed in following step:**
**[Using your testdata also resulted the same error**]

============================================================
 5) Evaluating repetitive regions (Mon Sep  3 16:51:20 CST 2018)
============================================================

        5.1- Running BlasR re-mapping.

        5.2- Running samtools view (Sam to Bam).

        5.3- Sorting bam file.

Use of uninitialized value $getmap01count in scalar chomp at /ds3200_1/proc/Organelle_PBA_1.0.8/OrganelleRef_PBA line 1344.
        5.4- Calculating coverage.

Illegal division by zero at /ds3200_1/proc/Organelle_PBA_1.0.8/OrganelleRef_PBA line 2266.

**Comment by aubombarely** [comment]
Okay, there was more pieces in the code that needed to be updated. Please check now if it works. Thanks.

**Comment by sanvva** [comment]
@aubombarely Yes,  it worked!  But, the blasR step is still very slow.

**Comment by aubombarely** [comment]
Single thread BlasR is slow. I recommend to use the option -b “--nproc=12”
or as many threads as you can use. Let me know if it fix the problem.
Usually the slowest step is the unitiging with Sprai.

**Comment by sanvva** [comment]
@aubombarely Yeah, multi-threads served better.
